export const API_ERROR = "EVENT/API_ERROR_RECEIVED";
export const WEATHER_DATA_RECEIVED = "EVENT/WEATHER_DATA_RECEIVED";

export const METRICS_DATA_RECEIVED = "EVENT/METRICS_DATA_RECEIVED";
export const NEW_MEASUREMENTS_RECEIVED = "EVENT/NEW_MEASUREMENT_DATA_RECEIVED";
export const METRICS_MEASUREMENTS_RECEIVED =
  "EVENT/METRICS_MEASUREMENTS_RECEIVED";

export const NEW_MEASUREMENTS_API_CALL_FAIL = "EVENT/NEW_MEASUREMENTS_API_CALL_FAIL";
export const METRIC_API_CALL_FAIL = "EVENT/METRIC_API_CALL_FAIL";
export const MULTIPLE_MEASUREMENTS_API_CALL_FAIL = 'EVENT/MULTIPLE_MEASUREMENTS_API_CALL_FAIL'

export const HEARTBEAT_UPDATED = "EVENT/HEARTBEAT_UPDATED";
export const DATA_NAME_RECEIVED = "EVENT/DATA_NAME_RECEIVED";
export const DATA_NAME_ADDED = "EVENT/DATA_NAME_ADDED";